version: '3'
services:
    mongodb:
        image: mongo
        container_name: viyyoor-mongodb
        volumes:
            - ../deployment/viyyoor/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - default
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    redis:
        image: redis
        container_name: viyyoor-redis
        restart: always
        networks:
            - default
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    web:
        build: .
        image: viyyoor-image
        container_name: viyyoor-web
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 9000:9000
        links:
            - mongodb
        networks:
            - default
        restart: always
        environment:
            VIYYOOR_SETTINGS: /app/viyyoor-production.cfg
        command:
          #uwsgi --lazy-apps --ini scripts/viyyoor-uwsgi.ini
          /venv/bin/gunicorn -w 4 --bind 0.0.0.0:9000 "viyyoor.web:create_app()"
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    worker:
        build: .
        image: viyyoor-image
        container_name: viyyoor-worker
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - mongodb
            - redis
        links:
            - mongodb
            - redis
        restart: always
        environment:
            VIYYOOR_SETTINGS: /app/viyyoor-production.cfg
        command:
            /venv/bin/viyyoor-worker
        logging:
            options:
                max-size: "10m"
                max-file: "3"

networks:
    default:
