[tool.poetry]
name = "viyyoor"
version = "0.0.1"
description = ""
authors = ["Thanathip Limna <boatkrap@gmail.com>"]

[tool.poetry.dependencies]
loginpass = "^0.5"
Flask-Login = "^0.5.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
viyyoor-web = "viyyoor.cmd.web:main"

[build-system]
